### ISSUE TITLE
Run on save [Feature request]

### ISSUE THREAD

**Issue by yannl35133** [ocamllabs/vscode-ocaml-platform#116] opened 2020-04-05 16:19 UTC
Could you add a "Run on save" option?

**Comment by rgrinberg** [comment] 2020-04-06 19:41
Could your describe the feature a little more? What does "run" mean exactly on an arbitrary module. It would be useful to show examples of other vscode extensions with such a feature.

**Comment by johnhaley81** [comment] 2020-04-06 19:48
@rgrinberg something that runs the compiler when a file is saved. Basically, when a change in a file is saved to disk, could the build system then be spun up to compile everything?

This is similar to how `autoRebuild` works in [reason-language-server](https://github.com/jaredly/reason-language-server/#configuration-settings)

**Comment by rgrinberg** [comment] 2020-04-06 19:50
What about running `$ dune build -w` as a task. Does that do what you want?

**Comment by yannl35133** [comment] 2020-04-06 20:02
In my case, I was thinking of type checking:

When I first open a file, all types are shown as `'_weak{n}`.
Ideally, the type-checker should run straight away to identify those types, but I'd like for it to run when I save the file (even with no changes). For now, I have to input something so that it identifies the types.

**Comment by johnhaley81** [comment] 2020-04-07 06:33
@rgrinberg `dune build -w` or `bsb make-world -w` would probably be a great first step!

**Comment by yannl35133** [comment] 2020-05-02 15:51
I did some tests with `dune build -w` to refine my idea.
When `dune build` (with or without `-w`) is run, the extension doesn't catch the update and run "merlin" on the file until a modification is made. That's why I would like you to add a feature so that saving also runs "merlin" and the new info is used without having to modify the file (in hope that this is easier to do).

Having an option to integrate `dune build -w` is not as interesting (at least to me), doing it manually is completely fine.

Finally, I have a question about how merlin works when used with dune : does it only check the definitions in built files, or can it check them in "live" files? Because, IIRC, without dune it can check in "live" files and no compilation is necessary to register changes for merlin.

**Comment by ulugbekna** [comment] 2021-06-25 10:28
Is this feature request still desired? 

> When I first open a file, all types are shown as '_weak{n}.
Ideally, the type-checker should run straight away to identify those types, but I'd like for it to run when I save the file (even with no changes). For now, I have to input something so that it identifies the types.

I fail to reproduce this

---

> does it only check the definitions in built files, or can it check them in "live" files?

AFAIU, merlin works with built files, so having `dune build -w` allows to have more up-to-date info with merlin. We also recently added "fetch diagnostics on save", which should make the experience better. 

---

Another note: there are `run on save` extensions in vscode marketplace if you'd like to run a certain vscode command or cli tool on save.

**Comment by yannl35133** [comment] 2021-06-25 10:52
I think "fetch diagnostics on save" is the feature I desired, but probably
failed to communicate clearly

**Comment by rgrinberg** [comment] 2021-06-27 20:12
> I think "fetch diagnostics on save" is the feature I desired, but probably
failed to communicate clearly

This now the case since ocamllsp 1.6.1.

> Finally, I have a question about how merlin works when used with dune : does it only check the definitions in built files, or can it check them in "live" files? Because, IIRC, without dune it can check in "live" files and no compilation is necessary to register changes for merlin.

When merlin is type checking a module it will use the source of the module + the build artifacts of all the dependencies of this module. In practice, almost all modules have some sort of dependencies on other compilation units, so it is required to run dune to generate the build artifacts first.

**Comment by ulugbekna** [comment] 2021-06-28 10:07
Should we close the issue if the problem no longer exists?

**Comment by rgrinberg** [comment] 2021-06-28 18:04
This solution still isn't perfect unfortunately. The diagnostic should update automatically after the build files change. But I think the current workaround addresses the issue described here.

**Closed by rgrinberg** 2021-06-28 18:04 UTC
Labels: type: feature
