### ISSUE TITLE
[Go to definition] doesn't work for values/types defined as part of dune-driven code generation

### ISSUE THREAD

**Issue by cemerick** [ocamllabs/vscode-ocaml-platform#524] opened 2021-02-05 20:29 UTC
I have a rule in my `dune` file like so:

```
(rule
 (target messages.ml)
 (action (with-stdout-to %{target}
           (run %{exe:messages/gen.exe} all %{dep:messages/messages.json}))))
```

It generates a `Messages` module using a separate small executable in the same project, driven by a source JSON file. That module is emitted to e.g. `_build/default/src/messages.ml`, which is appropriate and expected vis a vis dune as far as I can tell.

Unfortunately, the vscode extension seems to not know to look there for definitions within the same project, so `Go to definition` on a value or type defined in `Messages` yields "No definition found for ...". Of course, moving the generated source file to `src/messages.ml` helps the extension find and navigate to it via `Go to definition` as expected, but generating code into `src` is undesirable in general and non-idiomatic within dune (again, AFAICT).

**Comment by voodoos** [comment] 2021-02-22 14:50
I just reproduced the issue, and the error message from Merlin is:
`"'Messages.m' seems to originate from 'Messages' whose ML file could not be found"`

This is expected because in the generated merlin configuration the source directories do not include `_build` directories.

The obvious solution would be to add `_build/...` dirs to the source path but it is not clear if this would cause Merlin to jump wrongfully  inside the `_build` dir at some times (ie when jumping to a file which is both in the source tree and the build directory).

**Comment by cemerick** [comment] 2021-02-22 16:07
In other language ecosystems, there is an idiom of a designated "generated source" directory that tooling will expect and handle for these sorts of workflows. It seems like something similar would be appropriate here, covering both bespoke code generation like what I did in this case, but also more established tooling patterns e.g. cppo outputs?

**Comment by ulugbekna** [comment] 2021-11-07 18:47
Closing this, since the problem isn't a concern of this repo. A duplicate issue will remain in https://github.com/ocaml/ocaml-lsp/issues/470, feel free to subscribe if you'd like.

**Closed by ulugbekna** 2021-11-07 18:47 UTC
Labels: type: bug, upstream
