### ISSUE TITLE
Wrong doc comment displayed

### ISSUE THREAD

**Issue by carljohnesan** [ocamllabs/vscode-ocaml-platform#597] opened 2021-04-28 08:16 UTC
Hey, there! Thank you for this amazing extension!
I'm now learning OCaml by "Real World OCaml" book, and while writing code from examples, I've encountered a weird doc-comment bug, here's code:
```ocaml
open Base

type t

(** Blah *)
val empty : t
```
When I hover `empty`, I get the following doc hover:
"This module is the toplevel of the Base library; it's what you get when you write open Base.

The goal of Base is both to be a more complete standard library," etc

Here's the screenshot:
![doc_bug](https://user-images.githubusercontent.com/47556468/116370203-d7e63c80-a812-11eb-811f-018c26dd225e.png)

**Comment by ulugbekna** [comment] 2021-05-10 20:00
Duplicate of https://github.com/ocaml/ocaml-lsp/issues/344. Should be closed.

**Closed** 2021-05-10 20:01 UTC
