### ISSUE TITLE
Code lenses error "Illegal argument: character must be non-negative" (esy toolchain only)

### ISSUE THREAD

**Issue by jchavarri** [ocamllabs/vscode-ocaml-platform#240] opened 2020-06-01 12:58 UTC
Code lenses don't appear with `esy` toolchains in both `ml` and `re` files.

When looking into `Log (extension host)` output in vscode, I see:

```
[2020-06-01 14:55:26.485] [exthost] [error] [ocamllabs.ocaml-platform] provider FAILED
[2020-06-01 14:55:26.486] [exthost] [error] Error: Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:784)
	at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:426:473)
	at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:424:44)
	at d (/Users/javi/.vscode/extensions/ocamllabs.ocaml-platform-0.7.0/dist/extension.js:129:175415)
	at h (/Users/javi/.vscode/extensions/ocamllabs.ocaml-platform-0.7.0/dist/extension.js:129:175488)
	at N (/Users/javi/.vscode/extensions/ocamllabs.ocaml-platform-0.7.0/dist/extension.js:129:179857)
	at /Users/javi/.vscode/extensions/ocamllabs.ocaml-platform-0.7.0/dist/extension.js:129:184224
	at Array.map (<anonymous>)
	at asCodeLenses (/Users/javi/.vscode/extensions/ocamllabs.ocaml-platform-0.7.0/dist/extension.js:129:184217)
```

Note this only happens with esy toolchain. When using `opam` code lenses work ok.

Versions:
- macOS 10.15.4
- Extension: 0.7.0
- ocaml-lsp-server: `38bd51a` (I have tried with latest versions but still get the same error)

**Comment by rgrinberg** [comment] 2020-06-13 05:12
I don't think this is an issue with the esy setup. To confirm, run `$ dune clean` and then rebuild the project inside esy. This should work.

What I think the issue is that the usual magic number mismatch error `to be compiled with a version of OCaml` that leads to a dummy position being published. That should be fixed on the LSP side.

**Comment by rgrinberg** [comment] 2020-06-13 22:49
Here's a fix on the ocamllsp side to better present this error: https://github.com/ocaml/ocaml-lsp/pull/199

**Comment by rgrinberg** [comment] 2020-06-19 07:08
Please re-open if updating ocaml-lsp doesn't solve this problem.

**Closed by rgrinberg** 2020-06-19 07:08 UTC
