### ISSUE TITLE
Really slow analysis when using PPX

### ISSUE THREAD

**Issue by debugnik** [ocamllabs/vscode-ocaml-platform#247] opened 2020-06-05 18:20 UTC
Errors/warnings, completion and updates to code lenses become really slow when a project uses PPX. After a small edit, one can see red and yellow underlines advancing over the file, each update taking over a second, blocking all completion and updates to code lenses until all updates have finished. I've seen it take over two minutes until it unblocks; it's often faster to reload VS Code instead. Once it's unblocked, editing on a project that doesn't use PPX seems to work as fast as expected again.

Interestingly, the log for OCaml Language Server shows each message taking under 0.002s, but it logs completion events several seconds after I request them if it's too busy. It feels as if requests are being queued for a long time.

Note that I'm using WSL 2. This was more bearable when I was using WSL 1, which has faster I/O speeds for Windows volumes, but it was still noticeable.

**Comment by rgrinberg** [comment] 2020-06-13 23:03
Fundamentally, the issue is that merlin needs to re-run the preprocessor binary every time you update the document. That's bound to be high latency.

I've added some debouncing in an experimental branch, try it out and report if it helps performance: https://github.com/ocaml/ocaml-lsp/pull/181

**Comment by debugnik** [comment] 2020-06-13 23:27
Thanks! That's what I expected the issue to be, but I didn't know how to interpret the log timings. I'll try that branch tomorrow and report back.

**Comment by debugnik** [comment] 2020-06-17 15:15
I tried the branch you mentioned, but I'm afraid it didn't change much about the blocking, so I took a look at the code. The debouncing happens after each Merlin query has run, so the server still couldn't keep up with the notifications.

So I cloned the branch, moved the Merlin query inside the section scheduled by the timer and gave it a try. For burts of key presses, it solves the blocking issue. There's still latency after deboucing, but that's just how long Merlin takes. But if you stop typing for longer than the delay and then resume, the timer can trigger before Merlin has returned the previous query, blocking the server.

The ideal solution to the latter would be cancelling the work of the current query when the timer triggers. Not sure if that's possible but I'll try so I can submit a PR.

**Comment by rgrinberg** [comment] 2020-06-17 18:43
> The ideal solution to the latter would be cancelling the work of the current query when the timer triggers. Not sure if that's possible but I'll try so I can submit a PR.

Yeah, cancellation would improve the situation further. I'm planning on a general cancellation mechanism for all requests, but if you'd like to take a stab at it, that would be cool as well.

Another thing we should consider is debouncing code lens requests.

**Comment by rgrinberg** [comment] 2020-06-19 07:13
Another approach to solve this issue is to make lsp update the document only on save. It's not ideal, but it seems better than a slow user experience.

**Comment by jfrolich** [comment] 2020-07-09 05:53
I saw the debounce solution. Isn't it better to add back pressure to the language server calls? So there are no unnecessary delays?

**Comment by rgrinberg** [comment] 2020-07-09 05:56
Could you explain how would you use back pressure to solve this problem?

**Comment by jfrolich** [comment] 2020-07-09 06:06
I think the debounce is not really solving the issue. Just making it less worse. If you are overloading the server with async requests that are server-side processed serially you are just overflowing the "mailbox" of the server. (This will still happen with debouncing, only less requests are sent). If you add backpressure you can prevent that. Basically you refrain sending messages to the server until the server is finished processing.

**Comment by rgrinberg** [comment] 2020-07-09 06:19
Just so that we’re on the same page:

* vscode sends update notifications to the server whenever the source code changes.
* the lsp server pushes diagnostics to the client as a notification.

Since both of these processes are jsonrpc notifications, there are no responses to wait for in either case. Vscode will not wait and send us updates continuously. So where do we apply the back pressure?
	> Basically you refrain sending messages to the server until the server is finished processing.

How do we do that?

**Comment by jfrolich** [comment] 2020-07-09 06:42
Ok interesting. Where is the debounce implemented? I thought that was at the client level, but now I understand that you have no control over sending messages client side? Anyway. Even at the language server level you can implement something like this:

- have a queue of 1
- when a message comes in and the queue is taken, remove the pending message from the queue and replace it with the current
- when the in-process message is finished processing pick the next one in the queue or wait for a request

**Comment by rgrinberg** [comment] 2020-07-09 07:02
> Where is the debounce implemented? I thought that was at the client level, but now I understand that you have no control over sending messages client side

It’s implemented on the server side, and it’s out of our control as you said.

I’m not sure I full understand, but I'll try to rephrase. Isn't a queue of 1 just a `'a option ref`? The idea would be then to:

* Update this reference whenever a new document update is send by the client
* Diagnostics would be sent in a loop that would consume the value in this reference and send the diagnostics based on every iteration?

That would work decently but it would still have some performance pathologies. In particular, merlin is single threaded so while we're calculating diagnostics we can't do auto completion. The way the debounce is implemented prevents this. As you type, you are delaying diagnostics until you finish typing and hence the server is free to auto-complete.

**Comment by jfrolich** [comment] 2020-07-09 07:48
Two queues, one for diagnostics and one for autocomplete prioritizing autocomplete? (Sorry don't understand the architecture). Or a combination of the two with the 1 size queue to prevent mailbox overflow when working in (really) large files?

**Comment by rgrinberg** [comment] 2020-07-09 08:00
It's not just auto-completion. Almost all other requests require us to lock merlin. I don't understand what you'd like to improve by the way. There is no "mailbox overflow" problem. The client is sending us notifications that we process immediately and we don't buffer anything.

**Comment by jfrolich** [comment] 2020-07-09 08:46
I saw a screengrab that the LS is lagging tens of seconds behind the input. Process immediately can only be done if there is capacity right? What happens if the server is busy are those requests automatically discarded?

**Comment by rgrinberg** [comment] 2020-07-09 16:24
Those requests are enqueued. This problem isn't really related to diagnostics and you can make the server lag this way with any merlin request that's slow (completion, code actions, etc).

We could add some concurrency to handling the requests. Most requests require merlin to be executed, but in fact some common requests do not. I'm working on handling them concurrently in the future. Supporting cancellation will also improve performance in this regard.

**Comment by jfrolich** [comment] 2020-07-10 02:07
> Those requests are enqueued. This problem isn't really related to diagnostics and you can make the server lag this way with any merlin request that's slow (completion, code actions, etc).
> 
> We could add some concurrency to handling the requests. Most requests require merlin to be executed, but in fact some common requests do not. I'm working on handling them concurrently in the future. Supporting cancellation will also improve performance in this regard.

Cool, you know this much better, I am not familiar with the intricacies! 👍

**Comment by EduardoRFS** [comment] 2020-07-29 16:08
I think I'm hitting this frequently when messing with PPX, restart language server -> everything is working instantaneous -> 5 minutes later and is taking 10s to format a 1k lines of PPX

Especially this file, which generates a lot of code, it happens quite fast

> https://github.com/EduardoRFS/reason-css-parser/blob/9fab749e5af3d2fa4b9418aa43d908a575dd1d0f/lib/Parser.re

**Comment by tmattio** [comment] 2021-10-05 14:10
I believe @rgrinberg added support for request concurrency and request cancellation in the LSP server, so I'll close this issue, I don't think there's much more we can do on the extension side.

**Closed by tmattio** 2021-10-05 14:10 UTC

**Comment by rgrinberg** [comment] 2021-10-05 17:57
Another thing to note is that debouncing was essentially completely broken until ocamllsp 1.8.3. I would not be surprised if upgrading to that version fixed all these problems. With that being said, there's still a whole lot we can do to improve perf in the presence of ppx. It's just not something that can be done in this repo.
