### ISSUE TITLE
Syntax highlight incorrect for comments in unit `( (* comments in unit *) )`

### ISSUE THREAD

**Issue by arbipher** [ocamllabs/vscode-ocaml-platform#1209] opened 2023-08-31 19:12 UTC
`( (* comments in unit *) )` in vscode will be highlighted instead of turning grey as other comments.

I am unclear if it's a problem of this extension or ocaml-lsp.

**Comment by mnxn** [comment] 2023-09-19 02:32
Since the problem disappears when semantic highlighting is disabled in VS Code (using the `editor.semanticHighlighting.enabled` setting), the issue is with ocaml-lsp's semantic highlighting implementation.

You should create an issue in the ocaml-lsp repository if you haven't already.

**Comment by arbipher** [comment] 2023-09-19 02:56
Sure. I will create it soon later. Also, thanks for sharing the setting on how I can find the root cause.

**Comment by rgrinberg** [comment] 2023-09-25 22:58
Fixed in ocamllsp. Thanks!

**Closed by rgrinberg** 2023-09-25 22:58 UTC
