### ISSUE TITLE
"open a terminal (current sandbox)" fails with exit code 127

### ISSUE THREAD

**Issue by ulugbekna** [ocamllabs/vscode-ocaml-platform#280] opened 2020-07-08 10:01 UTC
`open a terminal (current sandbox)` fails with a message "The terminal process terminated with exit code: 127".

![terminal_open_fail](https://user-images.githubusercontent.com/16353531/86905469-62d63900-c112-11ea-91c5-1152e750de00.gif)

Opam switch: Using local switch based on `ocaml-lsp` opam file. The command fails for local switches only ("current" and "selected"). It works for a (selected) global switch.

OS: macOS Catalina

**Comment by rgrinberg** [comment] 2020-07-08 16:24
Could you paste the command that was invoked to run the terminal?  It should be logged in the debug console I believe.

**Comment by mnxn** [comment] 2020-07-08 16:36
On the latest version, logs for commands will be in the "OCaml Platform Extension" output channel:

![image](https://user-images.githubusercontent.com/25037249/86945906-7c6d8580-c0fe-11ea-9919-3089a5013ac0.png)

**Comment by ulugbekna** [comment] 2020-07-08 16:37
`getCommand: /usr/local/bin/opam exec --switch=/Users/ulugbekna/code/ocaml/ocaml-lsp --  -l` should be it.

**Comment by rgrinberg** [comment] 2020-07-08 16:39
I see. Did you set `shell.osx` somewhere?

**Comment by mnxn** [comment] 2020-07-08 16:39
It looks like its using an empty string for the shell command.

Have you set `ocaml.terminal.shell.osx` or `terminal.integrated.shell.osx` to something?

**Comment by ulugbekna** [comment] 2020-07-08 16:40
No, I shouldn't have.

**Comment by ulugbekna** [comment] 2020-07-08 16:41
Now, when I manually set `"ocaml.terminal.shell.osx": "zsh"`, it works fine.

**Comment by mnxn** [comment] 2020-07-08 16:45
What happens if you don't set `ocaml.terminal.shell.osx` to anything, but you set `terminal.integrated.shell.osx`?

**Comment by ulugbekna** [comment] 2020-07-08 16:47
When `ocaml.terminal.shell.osx` is *not* set and `terminal.integrated.shell.osx` is set, I get the same error.

**Comment by mnxn** [comment] 2020-07-08 17:02
This is very strange.

When the extension can't read `ocaml.terminal.shell.osx`, it's supposed to use `vscode.env.shell` here:
https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/src/TerminalSandbox.ml#L8

For some reason, it seems that the extension in your case is either

1. Thinking that `ocaml.terminal.shell.osx` is set to an empty string when it's actually not set to anything, or

2. Getting an empty string from `Env.shell`, when it should be the configured shell for the integrated terminal.

It shouldn't be possible for either option to happen.

I currently can't reproduce on my (Windows) computer.

**Comment by mnxn** [comment] 2020-07-08 17:03
> Opam switch: Using local switch based on ocaml-lsp opam file. The command fails for local switches only ("current" and "selected"). It works for a (selected) global switch.

What is the command that it uses for the global switch?

**Comment by ulugbekna** [comment] 2020-07-08 17:07
It shows `getCommand:  -l`. Strange. 

The logs look as follows: 

```json
external command {
  "cmd": "/usr/local/bin/opam",
  "args": "switch list -s",
  "result": {
    "exitCode": 0,
    "stdout": "/Users/ulugbekna/code/ocaml/cmdliner\n/Users/ulugbekna/code/ocaml/efftester\n/Users/ulugbekna/code/ocaml/merlin\n/Users/ulugbekna/code/ocaml/ocaml-lsp\n/Users/ulugbekna/code/ocaml/opam\nocaml4.09\n",
    "stderr": ""
  }
}

6 switches
getCommand:  -l
```

**Comment by ulugbekna** [comment] 2020-07-08 17:10
Anyway, maybe my config is messed up. We could ask someone else to reproduce.

**Closed** 2020-09-19 20:38 UTC
Labels: type: needs investigation
