### ISSUE TITLE
Sending OCaml expressions to a Toplevel?

### ISSUE THREAD

**Issue by MdeLv** [ocamllabs/vscode-ocaml-platform#215] opened 2020-05-19 23:42 UTC
I had to set up vscode for s.o. who doesn't know emacs at all. It was quite straightforward, just messing a little bit to setup build task (that has been changing over years). Once .merlin file are created, it works well (completion, jump to def, etc.).
I haven't yet noticed any limitation (while I never could have jaredly/reason-language-server working for unknown reason).

Within vscode, is there a way to launch a Toplevel and to send it the buffer, a region (selected/marked text) or just an Ocaml phrase (enclosing the cursor)?

btw, we could setup a build task (bound to C-S-b) but not several tasks. It's a pure vscode issue, but build, test, clean are three usual tasks that should be available at our finger tips.

Thanks

**Comment by rgrinberg** [comment] 2020-05-20 06:57
> btw, we could setup a build task (bound to C-S-b) but not several tasks. It's a pure vscode issue, but build, test, clean are three usual tasks that should be available at our finger tips.

That's a good idea. I believe this will require registering a task provider for dune https://code.visualstudio.com/api/references/vscode-api#tasks. I don't have much time to work on this in the short term, but if anyone else is interested, help would be appreciated.

**Comment by rgrinberg** [comment] 2020-05-20 06:57
> Within vscode, is there a way to launch a Toplevel and to send it the buffer, a region (selected/marked text) or just an Ocaml phrase (enclosing the cursor)?

There's no good solution for this unfortunately. We could add some emacs inspired commands, but it's not going to work very well. The toplevel situation in OCaml isn't so simple, see the `$ dune utop` command for the closest thing that we have to a useful toplevel inside a project.

**Comment by tmattio** [comment] 2021-02-08 11:00
Closing this as a duplicate of #504

**Closed by tmattio** 2021-02-08 11:00 UTC
