### ISSUE TITLE
"error: No esy project found"

### ISSUE THREAD

**Issue by theSherwood** [ocamllabs/vscode-ocaml-platform#563] opened 2021-03-13 08:46 UTC
Hi, I'm new to Reason. So I'm likely missing something simple, but I'm struggling to get a new project setup.

I cloned https://github.com/revery-ui/revery-quick-start/blob/master/src/App.re

I've run
`esy install`
`esy build`
in the root of that project.

I then tried restarting the language server.
Here is the output:

```
error: No esy project found (was looking from ~/code/mine/revery_7guis and up)
  
esy: exiting due to errors above
[Info  - 1:40:57 AM] Connection to server got closed. Server will restart.
error: No esy project found (was looking from ~/code/mine/revery_7guis and up)
  
esy: exiting due to errors above
[Info  - 1:40:57 AM] Connection to server got closed. Server will restart.
error: No esy project found (was looking from ~/code/mine/revery_7guis and up)
  
esy: exiting due to errors above
[Info  - 1:40:57 AM] Connection to server got closed. Server will restart.
error: No esy project found (was looking from ~/code/mine/revery_7guis and up)
  
esy: exiting due to errors above
[Info  - 1:40:57 AM] Connection to server got closed. Server will restart.
error: No esy project found (was looking from ~/code/mine/revery_7guis and up)
  
esy: exiting due to errors above
[Error - 1:40:57 AM] Connection to server got closed. Server will not be restarted.
```

Any help you could give me would be greatly appreciated.

**Comment by darcien** [comment] 2021-04-27 13:10
I'm not an ocaml expert, but I'm also trying out Revery UI.

I think the error is caused by different directory name in the `<PROJECT_ROOT>/.vscode/settings.json` vs your actual directory name.

If you check the `settings.json` inside the quick start repo, this file: https://github.com/revery-ui/revery-quick-start/blob/bb99424c629b92ee610f80dbe564ad8ccc1ed79c/.vscode/settings.json point the root directory to `"${workspaceFolder:revery-quick-start}"`, which does not exist if you clone the quick start repo to a directory with different name.

Looking at logs you pasted, seems like you clone it to `~/code/mine/revery_7guis`.

Can you try updating your `settings.json` to the correct path or just take it out for now just to see if it works or not?

If yes, then probably we should redirect this issue to revery-quick-start repo instead of here.

**Comment by tmattio** [comment] 2021-10-05 13:51
This sounds like a problem for either esy or revery, so I'm going to close this

**Closed by tmattio** 2021-10-05 13:51 UTC
