### ISSUE TITLE
Start with dune preview

### ISSUE THREAD

**Issue by nojaf** [ocamllabs/vscode-ocaml-platform#1627] opened 2024-10-21 13:54 UTC
Hello,

I've installed the Dune preview (https://preview.dune.build/)
How can I tell the extension that `dune tools exec ocamllsp` should be invoked to start the LSP server?

**Comment by voodoos** [comment] 2024-10-21 14:08
I think you should be able to enter `dune tools exec ocamllsp $prog $args` as a custom sandbox. You can set a custom sandbox by selecting the appropriate option in the list you get by clicking on the "opam" element in the status bar: 
<img width="104" alt="image" src="https://github.com/user-attachments/assets/fdb18be6-fe9d-4614-b054-1eba6a8d2309">
or by executing the `Ocaml: Select a sandbox for this workspace" command from the palette (ctrl+maj+p).

cc @gridbugs

**Comment by nojaf** [comment] 2024-10-21 14:45
That didn't work for me:

```
Error - 4:42:51 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:42:51 PM] Connection to server got closed. Server will restart.
true
[Error - 4:42:51 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:51 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:42:52 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:42:52 PM] Connection to server got closed. Server will restart.
true
[Error - 4:42:52 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:52 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:42:52 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:42:52 PM] Connection to server got closed. Server will restart.
true
[Error - 4:42:52 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:52 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:52 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:42:53 PM] Server process exited with code 2.
[Error - 4:42:53 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:42:53 PM] Connection to server got closed. Server will restart.
true
[Error - 4:42:53 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:53 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:42:53 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:53 PM] The OCaml Platform VS Code extension server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:42:53 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:53 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:42:53 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:43:10 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:43:10 PM] Connection to server got closed. Server will restart.
true
[Error - 4:43:10 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:10 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:43:11 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:43:11 PM] Connection to server got closed. Server will restart.
true
[Error - 4:43:11 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:11 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:43:11 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:43:11 PM] Connection to server got closed. Server will restart.
true
[Error - 4:43:11 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:11 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:11 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:43:12 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:43:12 PM] Connection to server got closed. Server will restart.
true
[Error - 4:43:12 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:12 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:12 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:43:12 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:12 PM] The OCaml Platform VS Code extension server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:43:12 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:12 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:43:12 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:44:37 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:44:37 PM] Connection to server got closed. Server will restart.
true
[Error - 4:44:37 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:37 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:44:37 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:44:37 PM] Connection to server got closed. Server will restart.
true
[Error - 4:44:37 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:37 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:44:38 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:44:38 PM] Connection to server got closed. Server will restart.
true
[Error - 4:44:38 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:44:38 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:44:38 PM] Connection to server got closed. Server will restart.
true
[Error - 4:44:38 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] Server process exited with code 2.
     Running 'ocamllsp ocamllsp'
_build/_private/default/.dev-tool/ocaml-lsp-server/ocaml-lsp-server/target/bin/ocamllsp: anonymous arguments aren't allowed.
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
  --version print version
  --fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
  --pipe set pipe path
  --socket set the port
  --port synonym for --socket
  --stdio set stdio
  --node-ipc not supported
  --clientProcessId set the pid of the lsp client
  -help  Display this list of options
  --help  Display this list of options
[Error - 4:44:38 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] The OCaml Platform VS Code extension server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:44:38 PM] OCaml Platform VS Code extension client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:44:38 PM] Server process exited with code 2.
```

**Comment by nojaf** [comment] 2024-10-21 20:26
```
halting dune merlin process
{ pid = pid 441577; initial_cwd = "/home/nojaf/projects/yozora_ppx" }
closed merlin process
{ pid = pid 441577; initial_cwd = "/home/nojaf/projects/yozora_ppx" }
    Building ocaml-config.3
[Error - 10:25:49 PM] Server process exited with code 0.
     Running 'ocamllsp'
[Warn  - 10:25:50 PM] failed to poll dune registry.
Unix.Unix_error(Unix.ENOENT, "stat", "/run/user/1000/dune/rpc")
Maybe you are not running dune in watch mode?
Hint: $ dune build -w
```

Hmm, still not quite working it seems.

**Comment by voodoos** [comment] 2024-10-22 08:27
@maiste @gridbugs any advice here ? I don't seem to find any documentation about this in the dune preview posts / website.

**Comment by nojaf** [comment] 2024-10-22 08:36
Gonna tag @leostera as well. He might be interested in this as well.

**Comment by maiste** [comment] 2024-10-22 08:44
IIRC a discussion with @electreAAS it was a bit tricky to make the tooling work with VS Code for now. I'm not aware of where it went....

**Comment by ElectreAAS** [comment] 2024-10-22 11:27
IIRC there were several issues:
- if we set up the sandbox command to be `foo $prog $args`, `foo` will be called once with args `ocamlc --version`, once with `ocamllsp --version`, and finally the normal command `ocamllsp`. We had a small shell script set up to redirect the first command to actually call `ocamlc`, and incorporate the latter ones with `dune tools exec`. This script is a workaround, we'd like a better solution in the future.
- Once the commands are actually dispatched correctly, the problem is that `ocamllsp` will call `ocamlformat` (and maybe vice-versa?), but without `dune` being aware of it and redirecting properly. Hence if you had it installed via opam that might get used. We discussed options but I don't think we have a working solution to this at the moment.

**Comment by voodoos** [comment] 2024-10-22 13:00
@nojaf as a workaround while waiting for the dune preview official support, you might be able to have a decently working setup by relying on an opam switch with the same version of OCaml as the one you use in the dune-pkg project and install the dev tools there.

**Comment by nojaf** [comment] 2024-10-22 14:45
Hmm, I'm a little too new to OCaml to figure that one out.
Perhaps if @ElectreAAS could post that shell script, it might be easier to wrap my head around.

**Comment by ElectreAAS** [comment] 2024-10-22 15:44
I'll have to agree with voodoos here: while exciting, the dune dev preview is not currently stable, and the integration with vscode is very much a work in progress.
If you still wish to use it, you can download [this script](https://github.com/gridbugs/dotfiles/blob/main/bin/ocamllsp.sh), make it executable, and ask vscode to run that: `/path/to/ocamllsp.sh $prog $args`

It should sort out this redirection problem, but again this is a dev preview, so things might break :shrug:

**Comment by nojaf** [comment] 2024-10-23 07:05
Thanks @ElectreAAS, this worked for me and was not so bad.

**Comment by smorimoto** [comment] 2024-11-26 16:18
I close this because the upstream documentation published the configuration instructions.

**Closed** 2024-11-26 16:17 UTC

**Comment by nojaf** [comment] 2024-11-26 16:33
Thanks a lot to all those involved!
