### ISSUE TITLE
Discovery of opam switches fails if one switch is empty

### ISSUE THREAD

**Issue by Khady** [ocamllabs/vscode-ocaml-platform#950] opened 2022-05-11 07:53 UTC
![image](https://user-images.githubusercontent.com/974142/167797190-aeb7e493-b92c-4dab-a38f-c096af2b6216.png)

When opening the ocaml menu from the sidebar this extension is trying to discover switches to list what packages they contain IIUC. The operation fails when there's at least one switch that is empty. It displays a popup with an error message:

```
ENOENT: no such file or directory, open '/home/louis.roche/.opam/ahrefs-placeholder/.opam-switch/switch-state'
```

This switch is created with `opam sw create ahrefs-placeholder --empty` so it doesn't contain any package, which probably explains why there's no `switch-state` file.

**Comment by ulugbekna** [comment] 2022-05-11 08:10
Hi Louis,
This is a duplicate of #791 and will be fixed soon :-)

**Closed by ulugbekna** 2022-05-11 08:10 UTC
