### ISSUE TITLE
Why is vscode-ocaml-platform fragile for some users?

### ISSUE THREAD

**Issue by gasche** [ocamllabs/vscode-ocaml-platform#1029] opened 2022-10-20 15:05 UTC
Hi there,

## Context

I came here from a reddit thread, [Is there a modern IDE with good support for OCaml?](https://www.reddit.com/r/ocaml/comments/y6p23u/is_there_a_modern_ide_with_good_support_for_ocaml/), where the reporter complains about the state of OCaml editor support *for them*, including the idea that vscode is "very buggy".

Those are strong words from a frustrated user, but the user (@mimoo) did do the kind work of gathering information and opening an issue on the bugtracker here:
  https://github.com/ocamllabs/vscode-ocaml-platform/issues/1020
and it appears from the report that they are correct in that vscode-ocaml-platform is very buggy *for them*. Quote:

> I use the extension in VSCode for different codebases, and I have to reselect the switch all the time
> I'm not sure why's that, or how to investigate, but resetting the switch by clicking on the same switch it's already using in the dropdown I showed above solves it for a few seconds/minutes.

Now there is approximatively one third of OCaml programmers using vscode, and for most of them vscode-ocaml-platform works very well! I certainly don't mean to suggest that the tool is buggy *in general*. But, looking at the issue tracker, it looks like there is a pattern of *some* users on *some* projects having a bad experience, with some shared symptoms.

[#970: Jump-to-definition stops working after a short while](https://github.com/ocamllabs/vscode-ocaml-platform/issues/970)

> I can repro over and over again, but it can take from a few seconds to a minute to repro. Basically, jump to definition locally within the file works for a while, then stops working. (And in the same way starts working again after a while).

## Question

It looks like vscode-ocaml-platform is fragile for some users, which in particular observe weirdly time-dependent behavior.

Question: are there systemic fixes that could make those sources of fragility go away, by making a part of the system more robust? At least, could it be easier for users to report and debug these issues?

vscode-ocaml-platform relies on ocaml-lsp that itself relies on Merlin, so that's a lot of moving pieces and it is hard to know where issues may come from.

(I asked @voodoos, who works on Merlin, if he had any idea of what may be causing those issues. He pointed out that Merlin is fragile for some queries, in particular "showing fully-expanded types", and that vscode tends to perform those queries more than Emacs due to the absence of an increasing-verbosity UI. Merlin itself guards against this fragility by catching exceptions instead of crashing, localizing the problem to a single query. But could it be that something else later in the pipeline does not handle these errors gracefully and crashes? This is a shot in the dark, but not inconsistent with the error trace in #1020.)

## Suggestions?

Some suggestions just from thinking about the problem for a bit.

1. My guess is that @mimoo has found a weird UI trick to restart the LSP server. It should be easier for users to discover how to work-around these issues when they arise. Would it be possible to have UI that gives information to the user on whether Merlin / the LSP server is currently running properly, or has crashed, with an explicit UI action to restart them? (In the old days we used GUI programs over the OCaml toplevel with a "restart the toplevel" function.)

2. When LSP or Merlin crashes, it should be easy for users to diagnose the issue and report relevant information here. Currently, judging from the lack of feedback on those issue reports, there isn't an easy way for vscode-ocaml-platform developers to tell users "get this log file, it should contain all the information we need to diagnose the problem". (Maybe there is a log file but it lacks the information.) Maybe add more logging around those unexpected failures?

**Comment by rgrinberg** [comment] 2022-10-20 23:18
I've looked into this and the issue is a serious bug that I've allowed in released versions of ocamllsp. The issue seems to be only reproducible in vscode (I have some conjectures as to why), which is why I've yet to run into it myself. It should be fixed in ocamllsp 1.14.1 hopefully. For now, you can pin ocamllsp in master and confirm if it resolves the issue.

Closing as this is an issue with ocamllsp and not the extension.

**Closed by rgrinberg** 2022-10-20 23:18 UTC

**Comment by rgrinberg** [comment] 2022-10-20 23:25
> Would it be possible to have UI that gives information to the user on whether Merlin / the LSP server is currently running properly, or has crashed, with an explicit UI action to restart them? (In the old days we used GUI programs over the OCaml toplevel with a "restart the toplevel" function.)

vscode already has a standard behavior that it sets. It allows every lsp server some small number of restarts before it gives up and tells the user the server is no longer usable. I'd prefer not to interfere with this behavior as it is what users already expect.
